baseURL = "https://cesaire.netlify.app/"
# baseURL = "https://localhost:1313/"
languageCode = "en-us"
title = "Mounah Honoré Césaire"
theme = "PaperMod"

[params]
  description = "Personal website and blog"
  author = "Mounah Honoré Césaire"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  disableSpecial1stPost = false
  displayFullLangName = true
  env = "development"

[params.profileMode]
enabled = true
title = "Mounah Honoré Césaire"
subtitle = "Ph.D Student in Operating Systems and Networking @ Inria, Rennes, France."
imageUrl = "profile.png"
imageTitle = "Cesaire M.H."

[[params.profileMode.buttons]]
name = "News"
url = "/news"

[[params.profileMode.buttons]]
name = "Projects"
url = "/projects"

[[params.profileMode.buttons]]
name = "Papers"
url = "/papers"

[[params.profileMode.buttons]]
name = "Resume"
url = "/resume"


[[params.socialIcons]]
name = "github"
url = "https://github.com/cesar237"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/cesairemh"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/cesar237"

[menu]
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "news"
name = "News"
url = "/news/"
weight = 20

[[menu.main]]
identifier = "publications"
name = "Publications"
url = "/papers/"
weight = 25

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 30 

[[menu.main]]
identifier = "resume"
name = "Resume"
url = "/resume/"
weight = 40
